version: "3"

services:
  n8n:
    image: wellalvesf/n8n-ffmpeg:latest
    container_name: n8n-ffmpeg
    ports:
      - "5679:5678"  # Porta externa 5679, interna continua 5678
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`flowffmpeg.sthub.com.br`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"  # Porta interna real
    environment:
      - N8N_HOST=flowffmpeg.sthub.com.br
      - N8N_PORT=5678  # Porta interna que o n8n escuta
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://flowffmpeg.sthub.com.br
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always
    networks:
      - sthub_net

volumes:
  n8n_data:

networks:
  sthub_net:
    external: true
