version: "3"

services:
  n8n:
    image: wellalvesf/n8n-ffmpeg:latest
    container_name: n8n-ffmpeg
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(\"flowffmpeg.sthub.com.br\")"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
    environment:
      - N8N_HOST=flowffmpeg.sthub.com.br
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://flowffmpeg.sthub.com.br
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always
    networks:
      - sthub_net

volumes:
  n8n_data:

networks:
  sthub_net:
    external: true
