version: "3.7"

services:
  n8n_ffmpeg:
    image: wellalvesf/n8n-ffmpeg:latest
    container_name: n8n-ffmpeg
    restart: always
    environment:
      - DB_TYPE=sqlite
      - N8N_HOST=flowffmpeg.sthub.com.br
      - N8N_EDITOR_BASE_URL=https://flowffmpeg.sthub.com.br/
      - WEBHOOK_URL=https://flowffmpeghook.sthub.com.br/
      - N8N_PROTOCOL=https
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - sthub_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true

        # Editor
        - traefik.http.routers.n8n_ffmpeg_editor.rule=Host(`flowffmpeg.sthub.com.br`)
        - traefik.http.routers.n8n_ffmpeg_editor.entrypoints=websecure
        - traefik.http.routers.n8n_ffmpeg_editor.priority=1
        - traefik.http.routers.n8n_ffmpeg_editor.tls.certresolver=letsencryptresolver
        - traefik.http.routers.n8n_ffmpeg_editor.service=n8n_ffmpeg_editor
        - traefik.http.services.n8n_ffmpeg_editor.loadbalancer.server.port=5678
        - traefik.http.services.n8n_ffmpeg_editor.loadbalancer.passHostHeader=true

        # Webhook
        - traefik.http.routers.n8n_ffmpeg_webhook.rule=Host(`flowffmpeghook.sthub.com.br`)
        - traefik.http.routers.n8n_ffmpeg_webhook.entrypoints=websecure
        - traefik.http.routers.n8n_ffmpeg_webhook.priority=1
        - traefik.http.routers.n8n_ffmpeg_webhook.tls.certresolver=letsencryptresolver
        - traefik.http.routers.n8n_ffmpeg_webhook.service=n8n_ffmpeg_webhook
        - traefik.http.services.n8n_ffmpeg_webhook.loadbalancer.server.port=5678
        - traefik.http.services.n8n_ffmpeg_webhook.loadbalancer.passHostHeader=true

volumes:
  n8n_data:

networks:
  sthub_net:
    external: true
